### ISSUE TITLE
Using promo code with 100% discount throws error

### ISSUE THREAD

**Issue by bfolkens** [ozziexsh/bling#7]
When creating a subscription using a coupon with a 100% discount, the `payment_intent` field is `nil`, leading to the following exception:

```elixir
** (RuntimeError) You must provide an ID or a struct with an ID to this operation.
    (stripity_stripe 2.17.3) lib/stripe/request.ex:156: Stripe.Request.get_id!/1
    (stripity_stripe 2.17.3) lib/stripe/core_resources/payment_intent.ex:182: Stripe.PaymentIntent.retrieve/3
    (bling 0.4.0) lib/bling/customers.ex:325: Bling.Customers.create_subscription/2
```

**Comment by bfolkens** [comment]
We've patched this internally on a fork so will submit a patch shortly.
